const fs = require('fs');

let css = fs.readFileSync('assets/index-DpdlmGVI.css', 'utf8');

const targetOld = '.inline-payment{background:linear-gradient(135deg,#282035,#1b1726);border:1px solid #a8794f52;border-radius:1rem;grid-template-columns:1fr 72px;align-items:center;gap:14px;margin-top:22px;padding:14px;display:grid}.inline-payment-title{color:#f3e5d7;align-items:center;gap:7px;font-size:11px;font-weight:700;display:flex}.esewa-dot.small{width:20px;height:20px;margin-right:0;font-size:14px}.inline-payment p{color:#a99cab;margin-top:5px;font-size:10px;line-height:1.5}.inline-payment img{object-fit:contain;background:#fff;border-radius:.55rem;grid-area:1/2/span 2;width:72px;height:88px;padding:4px}.inline-payment-amounts{flex-wrap:wrap;gap:5px;margin-top:10px;display:flex}.inline-payment-amounts span{color:#a99cab;background:#ffffff12;border-radius:.4rem;padding:4px 6px;font-size:8px}.inline-payment-amounts b{color:#e1b671}.inline-payment>a{color:#fff;background:#1f8f5a;border-radius:999px;grid-column:1/-1;justify-content:center;align-items:center;gap:5px;padding:8px 10px;font-size:10px;font-weight:700;display:inline-flex}';

const replacement = `.inline-payment{background:linear-gradient(135deg,#2a2138,#181424);border:1px solid rgba(225,182,113,0.35);border-radius:1.25rem;grid-template-columns:1fr 220px;align-items:center;gap:22px;margin-top:24px;padding:22px;display:grid;box-shadow:0 12px 35px rgba(0,0,0,0.35)}.inline-payment-title{color:#f8eee3;align-items:center;gap:9px;font-size:13.5px;font-weight:700;display:flex}.esewa-dot.small{width:24px;height:24px;margin-right:0;font-size:16px;display:inline-flex;align-items:center;justify-content:center}.inline-payment p{color:#c2b5c5;margin-top:6px;font-size:11.5px;line-height:1.6}.inline-payment-amounts{flex-wrap:wrap;gap:6px;margin-top:12px;display:flex}.inline-payment-amounts span{color:#d8ccd9;background:#ffffff18;border:1px solid rgba(255,255,255,0.08);border-radius:0.5rem;padding:5px 9px;font-size:10.5px}.inline-payment-amounts b{color:#f0c37b;font-weight:600}.inline-payment img{object-fit:contain;background:#fff;border-radius:0.75rem;width:100%;max-width:210px;height:auto;aspect-ratio:1296/2022;padding:8px;box-shadow:0 8px 24px rgba(0,0,0,0.45);cursor:pointer;transition:transform 0.2s ease,box-shadow 0.2s ease;display:block}.inline-payment img:hover{transform:scale(1.03);box-shadow:0 12px 32px rgba(0,0,0,0.65)}.qr-payment-wrap{flex-direction:column;align-items:center;gap:8px;display:flex}.qr-name-note{color:#d6c7d7;text-align:center;max-width:210px;font-size:11px;line-height:1.45;font-weight:500}.inline-payment>a{color:#fff;background:#1f8f5a;border-radius:999px;grid-column:1/-1;justify-content:center;align-items:center;gap:8px;padding:12px 18px;font-size:13px;font-weight:700;display:inline-flex;transition:background 0.2s ease,transform 0.15s ease;box-shadow:0 4px 15px rgba(31,143,90,0.35)}.inline-payment>a:hover{background:#25a86a;transform:translateY(-2px)}@media (max-width:640px){.inline-payment{grid-template-columns:1fr;text-align:center;gap:18px;padding:18px 16px}.inline-payment-title{justify-content:center}.inline-payment-amounts{justify-content:center}.inline-payment img{margin:0 auto;max-width:200px}}`;

if (!css.includes(targetOld)) {
  console.error('Old target string not found in index-DpdlmGVI.css!');
  process.exit(1);
}

css = css.replace(targetOld, replacement);
fs.writeFileSync('assets/index-DpdlmGVI.css', css, 'utf8');
console.log('Successfully updated assets/index-DpdlmGVI.css with clear, prominent QR styling!');
